<a href="https://colab.research.google.com/github/Natsutoshi/python_practice/blob/main/Pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install torch torchvision

In [ ]:
import torch
import numpy as np
np.set_printoptions(precision=3)
a = [1,2,3]
b=np.array([4,5,6], dtype=np.int32)
t_a=torch.tensor(a)
t_b=torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [ ]:
t = torch.rand(3,5)
print(t)
t_tr=torch.transpose(t,0,1)
print(t_tr)

tensor([[0.8401, 0.4996, 0.7345, 0.3410, 0.2745],
        [0.9332, 0.9754, 0.7061, 0.3434, 0.2375],
        [0.7999, 0.3739, 0.7624, 0.8814, 0.5511]])
tensor([[0.8401, 0.9332, 0.7999],
        [0.4996, 0.9754, 0.3739],
        [0.7345, 0.7061, 0.7624],
        [0.3410, 0.3434, 0.8814],
        [0.2745, 0.2375, 0.5511]])


In [ ]:
t_2=torch.rand(3,5,7)
print(t_2)

tensor([[[0.0042, 0.8021, 0.4959, 0.4745, 0.7128, 0.1334, 0.7427],
         [0.7938, 0.3083, 0.8594, 0.0213, 0.2731, 0.6461, 0.0260],
         [0.1676, 0.4456, 0.2569, 0.4759, 0.9710, 0.2809, 0.5204],
         [0.4852, 0.0581, 0.8934, 0.7705, 0.9241, 0.3747, 0.6273],
         [0.3394, 0.5242, 0.8256, 0.4559, 0.3400, 0.1845, 0.0883]],

        [[0.9696, 0.4712, 0.8072, 0.0845, 0.5279, 0.8218, 0.5936],
         [0.2572, 0.5715, 0.1489, 0.6485, 0.4591, 0.4083, 0.4425],
         [0.5771, 0.6883, 0.9649, 0.1834, 0.2965, 0.3577, 0.2165],
         [0.8367, 0.1273, 0.5824, 0.8763, 0.3325, 0.0083, 0.1351],
         [0.2936, 0.3422, 0.4686, 0.3690, 0.7327, 0.4868, 0.0901]],

        [[0.9325, 0.8151, 0.4739, 0.4792, 0.3119, 0.6645, 0.2507],
         [0.6670, 0.6967, 0.9715, 0.6448, 0.4836, 0.6050, 0.0389],
         [0.7736, 0.3299, 0.2441, 0.7772, 0.8659, 0.4060, 0.7551],
         [0.0264, 0.0737, 0.6870, 0.7531, 0.2853, 0.4237, 0.3338],
         [0.3562, 0.6041, 0.7099, 0.6706, 0.5333, 0.8422, 

In [ ]:
t_2np=t_2.clone().numpy()
print(t_2np)

[[[0.004 0.802 0.496 0.474 0.713 0.133 0.743]
  [0.794 0.308 0.859 0.021 0.273 0.646 0.026]
  [0.168 0.446 0.257 0.476 0.971 0.281 0.52 ]
  [0.485 0.058 0.893 0.771 0.924 0.375 0.627]
  [0.339 0.524 0.826 0.456 0.34  0.184 0.088]]

 [[0.97  0.471 0.807 0.084 0.528 0.822 0.594]
  [0.257 0.571 0.149 0.649 0.459 0.408 0.442]
  [0.577 0.688 0.965 0.183 0.296 0.358 0.217]
  [0.837 0.127 0.582 0.876 0.333 0.008 0.135]
  [0.294 0.342 0.469 0.369 0.733 0.487 0.09 ]]

 [[0.933 0.815 0.474 0.479 0.312 0.664 0.251]
  [0.667 0.697 0.972 0.645 0.484 0.605 0.039]
  [0.774 0.33  0.244 0.777 0.866 0.406 0.755]
  [0.026 0.074 0.687 0.753 0.285 0.424 0.334]
  [0.356 0.604 0.71  0.671 0.533 0.842 0.187]]]
